= Make Zurich: LoRaWAN hacker/maker event

This is an initiative of the city of Zurich and the community to promote an open and shared IoT infrastructure and data exchange.

== Status

Initial planning.

== Goals

* Improve the city of Zurich with smart ideas and technology
* Work towards a reliable, shared and open infrastructure for organizations and individuals
* The infrastructure is to be made available to interested organizations and individuals
* Context: Smart City/Open Data

== Ideas

* Define/setup demo infrastructure
* Collect real world use cases from the city and quartiervereine
* Besides the real world use cases, there should always be a 'free track' to hack on any other problem
* Promote the goals of an open and shared IoT infrastructure with a hacker/maker challenge
* Demonstrate the ability to implement real world use cases
* Use successful use cases to further promote the goals

== Next meeting

* 26th September, 17:00 @ Impact Hub Zurich, Auer & Co. Cafe

== Summary

=== Name
The event is called `Make Zurich`. It has a more possitive tone to it than `Hack x` and it leverages the *maker movement* as a primary component of it.

=== Date
The **tentative** date of the event is end of January 2017.

=== Location
Impact Hub Zurich

=== Format
The event extends for one full week using the following structure:

==== Event kickoff: Friday 27th January

The event starts with a presentation of use cases (challenges) by the City of Zurich and other stakeholders (e.g. Quartiervereine) on Friday afternoon. The hardware components required for the various challenges is made available to participants.

Presentations are followed by an apero where participants can meet and form teams.

Team registration is open until the end of the evening.

==== Open Lab week

From Saturday to next Friday evening (inclusive), an OpenLab week is be available at the Impact Hub Zurich (perhaps in partnership with https://zurich.impacthub.ch/de/community/makerzspace-tribe/[MakerZspace tribe]?).

Participants can walk-in, use the facilities and work on their projects, but there won't be an active tutoring/mentoring in-place.

==== Hackathon: Saturday 4th and Sunday 5th February

On Saturday morning, a more intense session begins: following more traditional hackathon schedules, participants get together to work on their projects for the weekend (maybe 32-hours? starting on Sat 8:00, ending on Sun 16:00?), after which the event closes on Sunday afternoon with the presentation of all projects.

=== Use cases

Still in progress. The initial list of challenges can be found https://drive.google.com/open?id=0B_DO0nUUQCrhRzBEMzhpVTlHR3M[on Google Drive].

=== Infrastructure

The community network of The Things Network Zurich is used as communication link to implement use cases.

A storage and visualization infrastructure (potentially based on Grafana) will be provided for the participants.

== TODOs
* [ ] After feedback, we all will prioritize and decide on a sub-set of use cases, the estimate and budget for them, to enable sourcing all components required with enough time.
* [ ] Simon will confirm with Andreas and Dennis about organization, logistics, budget, etc.
* [ ] Simon/Andreas/Dennis will confirm if we can rent or partner to get some space at the Impact Hub for the OpenLab week. Perhaps in partnership with https://zurich.impacthub.ch/de/community/makerzspace-tribe/[MakerZspace tribe]?
* [ ] Gonzalo will arrange the details to get the infrastructure ready, including storage and visualization.
* [ ] Confirm marketing material for the event. We prepared the following link:marketing-ideas.adoc[tentative ideas for a logo], but probably we need to go for a more professional design.
* [ ] Check if Decentlab wants to be sponsor. Maybe even sponsor some equipment?
* [ ] Identify interested stakeholders from the city and quartiervereine with real world challenges. Almost done, probably going to be completed with the fact sheet.
* [x] Simon will send Outlook invites for next meeting.
* [x] Simon will prepare a fact sheet for the EWZ use cases and pass it on to Open Data Zurich
* [x] Reto and Michael will add Open Data Zurich use cases to it, and pass it on to TTN Community
* [x] Urs and Gonzalo will add TTN community use cases to it and send back.
* [x] After fact sheet is ready, Gonzalo will present it to the community team that will be helping out with some of the organization.
* [x] Check existing TTN efforts regarding security review (for potentially operating the platform on city infra):
** [x] Johan Stokking (tech lead of TTN Global) confirmed that they will have an audit done by http://deloitte.com/ch/en.html[Deloitte].
* [x] Check community interest for such a challenge (IoT, Java, JavaScript, Open Data):
** [x] Community is definitely up for it. Six members of the community signed up to help out. There's a group forming on TTN-CH Slack for this purpose.

=== AsciiDoctor Format

This document is written in the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoctor] format. 
