= Make Zurich

*Civic tech and LoRaWAN hackathon for a better city*

This is an initiative of the city of Zurich and the community to promote an open and shared IoT infrastructure and data exchange.

== Goals

* Improve the city of Zurich with smart ideas and technology
* Work towards a reliable, shared and open infrastructure for organizations and individuals
* The infrastructure is to be made available to interested organizations and individuals
* Context: Smart City/Open Data

== Ideas

* Collect real world use cases from the city and Quartiervereine
* Besides the real world use cases, an open challenge will allow to hack freely on any other problem
* Promote the goals of an open and shared IoT infrastructure with a hacker/maker challenge
* Demonstrate the ability to implement real world use cases
* Use successful use cases to further promote the goals

== Summary

=== Name
The event is called `Make Zurich`. It has a more possitive tone to it than `Hack x` and it leverages the *maker movement* as a primary component of it.

=== Date
The date of the event is end of January/beginning of February 2017.

=== Location
Impact Hub Zurich at Viadukt https://zurich.impacthub.ch/space/bogen_d/[Event Space Bogen D]

=== Format
The event extends for one full week using the following structure:

==== Event kickoff: Friday 27th January

The event starts with a presentation of use cases (challenges) by the City of Zurich and other stakeholders (e.g. Quartiervereine) on Friday afternoon. The hardware components required for the various challenges is made available to participants.

Presentations are followed by an apero where participants can meet and form teams.

Team registration is open until the end of the evening.

==== Open Lab week

From Saturday to next Friday evening (inclusive), an OpenLab week is be available at (location to be confirmed).

Participants can walk-in, use the facilities and work on their projects, but there won't be an active tutoring/mentoring in-place.

==== Hackathon: Friday 3rd and Saturday 4th February

On Friday morning, a more intense session begins: following more traditional hackathon schedules, participants get together to work on their projects for the weekend (maybe 32-hours? starting on Friday 9:00, ending on Saturday 17:00), after which the event closes on Saturday afternoon with the presentation of all projects.

=== Challenges

The list of challenges can be found https://drive.google.com/open?id=0B_DO0nUUQCrhRzBEMzhpVTlHR3M[on Google Drive]. Although still draft, it has been prioritized and some challenges have been already ruled out to keep focus.

In order to prioritize the challenges, the TTN community provided ranked feedback about preferences; these votes were fed into a Condorcet vote system (Schulze) that determined the order in which they appear on the document. The https://www.condorcet.vote/Vote/EDAFC0A08A/[vote can be publicly accessed here].

=== Infrastructure

The community network of The Things Network Zurich is used as communication link to implement use cases.

A storage and visualization infrastructure will be provided for the participants. Tentatively based on http://grafana.org/[Grafana] + https://www.mongodb.com/[MongoDB] or the https://www.influxdata.com/time-series-platform/influxdb/[TICK Stack] (composed by InfluxDB + friends).

The project board for the event will be based on https://datalets.ch/dribdat/[Dribdat] (by https://github.com/loleg/[Oleg] - see http://dribdat.soda.camp/event/4[Example]).

The communication channel during the event will be https://slack.com/[Slack].

The primary event's website will be http://makezurich.ch[makezurich.ch].

=== AsciiDoctor Format

This document is written in the http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoctor] format. 
